version: '3'
services:
  web:
    image: "composer"
    volumes:
      - .:/app
    ports:
      - "8041:8041"
    command: [ "php", "-S", "0.0.0.0:8041", "-t", "/app/public" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8041"]
